In [449]:
import pandas as pd

df = pd.read_csv("Combined_dataset.csv")
print(df)

     product_id           title  \
0       8376765     Lino Perros
1       9136281  Tommy Hilfiger
2      17633752           Lavie
3       1376949          F Gear
4      13939916       MYTRIDENT
..          ...             ...
995    13698258           KREDO
996    16896006           GUESS
997     1708108        GIORDANO
998    19280114        Fastrack
999    18601682         BOLDFIT

                                   product_description  rating  ratings_count  \
0                       Women Navy Blue Solid Backpack     3.8             15
1                    Unisex Navy Blue Striped Backpack     4.5             67
2                       Aries Women Pink Mini Backpack     4.4            226
3           Unisex Navy & Grey Printed Burner Backpack     4.4           1052
4                             Men Blue Solid Bath Robe     4.7             12
..                                                 ...     ...            ...
995  Men FORTE Silver Automatic Skeleton Analogue W...     3.5             11
996  Women White Patterned Dial & White Straps Anal...     5.0             22
997  Women Rose Gold-Toned Mirrored Analogue Watch ...     2.8              5
998  Men Black Brass Dial & Black Stainless Steel S...     4.3             17
999                           Purple Textured Yoga Mat     3.8            161

     initial_price  discount   final_price currency  \
0             3995      58.0   "₹3,995.00"      INR
1             2899      35.0   "₹2,899.00"      INR
2             2999      65.0   "₹2,999.00"      INR
3             1675      52.0   "₹1,675.00"      INR
4             2899      17.0   "₹2,899.00"      INR
..             ...       ...           ...      ...
995          11890      50.0  "₹11,890.00"      INR
996           8900      45.0   "₹8,900.00"      INR
997           7950      50.0   "₹7,950.00"      INR
998           3295      20.0   "₹2,636.00"      INR
999            699      31.0     "₹699.00"      INR

                                                images  ...  \
0    http://assets.myntassets.com/assets/images/837...  ...
1    http://assets.myntassets.com/assets/images/913...  ...
2    http://assets.myntassets.com/assets/images/176...  ...
3    http://assets.myntassets.com/assets/images/137...  ...
4    http://assets.myntassets.com/assets/images/pro...  ...
..                                                 ...  ...
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
0    {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1    {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2    {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3    {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4    {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
..                                                 ...                 ...
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                                              sizes  \
0               NaN                               [{"size":"Onesize"}]
1               NaN                               [{"size":"Onesize"}]
2               NaN                                     [{"size":"S"}]
3               NaN                               [{"size":"Onesize"}]
4               NaN  [{"size":"M","value":"45.0in","value_name":"Fr...
..              ...                                                ...
995             NaN                               [{"size":"Onesize"}]
996             NaN                               [{"size":"Onesize"}]
997             NaN                               [{"size":"Onesize"}]
998  Tru███m R███il                               [{"size":"Onesize"}]
999             NaN                                [{"size":"Medium"}]

                                                videos  \
0                                ["rw-8376765_cae700"]
1                                ["rw-9136281_cae700"]
2    ["https://videos.myntassets.com/assets/videos/...
3    ["https://videos.myntassets.com/assets/videos/...
4                                                  NaN
..                                                 ...
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                                      variations  \
0                                           [{}]
1                                        [{},{}]
2                            [{},{},{},{},{},{}]
3                                            NaN
4    [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
..                                           ...
995                                          NaN
996                                          NaN
997                    [{},{},{},{},{},{},{},{}]
998                                          NaN
999                                [{},{},{},{}]

                                            best_offer  \
0                                                   {}
1                                                   {}
2                                                   {}
3                                                   {}
4                                                   {}
..                                                 ...
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
0    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4    [{"offer_name":"10% Instant Discount on IndusI...  bath-robe
..                                                 ...        ...
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[1000 rows x 24 columns]

In [450]:
print(df.head())

   product_id           title                         product_description  \
0     8376765     Lino Perros              Women Navy Blue Solid Backpack
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe

   rating  ratings_count  initial_price  discount  final_price currency  \
0     3.8             15           3995      58.0  "₹3,995.00"      INR
1     4.5             67           2899      35.0  "₹2,899.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
4     4.7             12           2899      17.0  "₹2,899.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/837...  ...
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
4  http://assets.myntassets.com/assets/images/pro...  ...

                                     amount_of_stars what_customers_said  \
0  {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN

  seller_name                                              sizes  \
0         NaN                               [{"size":"Onesize"}]
1         NaN                               [{"size":"Onesize"}]
2         NaN                                     [{"size":"S"}]
3         NaN                               [{"size":"Onesize"}]
4         NaN  [{"size":"M","value":"45.0in","value_name":"Fr...

                                              videos seller_information  \
0                              ["rw-8376765_cae700"]                NaN
1                              ["rw-9136281_cae700"]                NaN
2  ["https://videos.myntassets.com/assets/videos/...                NaN
3  ["https://videos.myntassets.com/assets/videos/...                NaN
4                                                NaN                NaN

                                    variations best_offer  \
0                                         [{}]         {}
1                                      [{},{}]         {}
2                          [{},{},{},{},{},{}]         {}
3                                          NaN         {}
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]         {}

                                         more_offers   category
0  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4  [{"offer_name":"10% Instant Discount on IndusI...  bath-robe

[5 rows x 24 columns]

In [451]:
print(df.tail(5))

     product_id     title                                product_description  \
995    13698258     KREDO  Men FORTE Silver Automatic Skeleton Analogue W...
996    16896006     GUESS  Women White Patterned Dial & White Straps Anal...
997     1708108  GIORDANO  Women Rose Gold-Toned Mirrored Analogue Watch ...
998    19280114  Fastrack  Men Black Brass Dial & Black Stainless Steel S...
999    18601682   BOLDFIT                           Purple Textured Yoga Mat

     rating  ratings_count  initial_price  discount   final_price currency  \
995     3.5             11          11890      50.0  "₹11,890.00"      INR
996     5.0             22           8900      45.0   "₹8,900.00"      INR
997     2.8              5           7950      50.0   "₹7,950.00"      INR
998     4.3             17           3295      20.0   "₹2,636.00"      INR
999     3.8            161            699      31.0     "₹699.00"      INR

                                                images  ...  \
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                 sizes  \
995             NaN  [{"size":"Onesize"}]
996             NaN  [{"size":"Onesize"}]
997             NaN  [{"size":"Onesize"}]
998  Tru███m R███il  [{"size":"Onesize"}]
999             NaN   [{"size":"Medium"}]

                                                videos  \
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                    variations  \
995                        NaN
996                        NaN
997  [{},{},{},{},{},{},{},{}]
998                        NaN
999              [{},{},{},{}]

                                            best_offer  \
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[5 rows x 24 columns]

In [452]:
print(df.shape)

(1000, 24)

In [453]:
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [454]:
print(df.dtypes)

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [455]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB
None

In [456]:
print(df.describe())

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [457]:
print(df.isnull())

     product_id  title  product_description  rating  ratings_count  \
0         False  False                False   False          False
1         False  False                False   False          False
2         False  False                False   False          False
3         False  False                False   False          False
4         False  False                False   False          False
..          ...    ...                  ...     ...            ...
995       False  False                False   False          False
996       False  False                False   False          False
997       False  False                False   False          False
998       False  False                False   False          False
999       False  False                False   False          False

     initial_price  discount  final_price  currency  images  ...  \
0            False     False        False     False   False  ...
1            False     False        False     False   False  ...
2            False     False        False     False   False  ...
3            False     False        False     False   False  ...
4            False     False        False     False   False  ...
..             ...       ...          ...       ...     ...  ...
995          False     False        False     False   False  ...
996          False     False        False     False   False  ...
997          False     False        False     False   False  ...
998          False     False        False     False   False  ...
999          False     False        False     False   False  ...

     amount_of_stars  what_customers_said  seller_name  sizes  videos  \
0              False                 True         True  False   False
1              False                 True         True  False   False
2              False                 True         True  False   False
3              False                 True         True  False   False
4              False                 True         True  False    True
..               ...                  ...          ...    ...     ...
995            False                 True         True  False   False
996            False                 True         True  False   False
997            False                 True         True  False    True
998            False                 True        False  False    True
999            False                 True         True  False    True

     seller_information  variations  best_offer  more_offers  category
0                  True       False       False        False     False
1                  True       False       False        False     False
2                  True       False       False        False     False
3                  True        True       False        False     False
4                  True       False       False        False     False
..                  ...         ...         ...          ...       ...
995                True        True       False        False     False
996                True        True       False        False     False
997                True       False       False        False     False
998               False        True       False        False     False
999                True       False       False        False     False

[1000 rows x 24 columns]

In [458]:
print(df.isnull().sum())

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [459]:
df = df.dropna(subset=['product_id'])
print(df.isnull().sum())

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [460]:
df = df.fillna(0)
print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [461]:
filtered_df = df[df['initial_price'] > 2000]
filtered_df[['title', 'initial_price']].head()

            title  initial_price
0     Lino Perros           3995
1  Tommy Hilfiger           2899
2           Lavie           2999
4       MYTRIDENT           2899
7         My Room           2999

In [462]:
jeans_df = df[df['category'] == "jeans"]
jeans_df[['title', 'category']].head()

                  title category
374               Levis    jeans
375               Levis    jeans
376  Calvin Klein Jeans    jeans
377               Levis    jeans
378               KETCH    jeans

In [463]:
premium_jeans_df = df[(df['category'] == "jeans") & (df['initial_price'] > 2000)]
premium_jeans_df[['title', 'category', 'initial_price']].head()

                  title category  initial_price
374               Levis    jeans           4099
375               Levis    jeans           4399
376  Calvin Klein Jeans    jeans           7999
377               Levis    jeans           4399
380                 Lee    jeans           3799

In [464]:
selected_columns_df = df[['product_id', 'title', 'initial_price']]
selected_columns_df.head()

   product_id           title  initial_price
0     8376765     Lino Perros           3995
1     9136281  Tommy Hilfiger           2899
2    17633752           Lavie           2999
3     1376949          F Gear           1675
4    13939916       MYTRIDENT           2899

In [465]:
df.duplicated().sum()
#There is no duplicate value in the dataset so we don't need to drop any duplicate value.

np.int64(0)

In [466]:
df['final_price'] = df['final_price'].astype(str).str.replace(r'[^\d.]', '', regex=True)
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')
df.to_csv('cleaned_dataset.csv', index=False, encoding='utf-8-sig')
df[['title', 'initial_price', 'final_price']]

              title  initial_price  final_price
0       Lino Perros           3995       3995.0
1    Tommy Hilfiger           2899       2899.0
2             Lavie           2999       2999.0
3            F Gear           1675       1675.0
4         MYTRIDENT           2899       2899.0
..              ...            ...          ...
995           KREDO          11890      11890.0
996           GUESS           8900       8900.0
997        GIORDANO           7950       7950.0
998        Fastrack           3295       2636.0
999         BOLDFIT            699        699.0

[1000 rows x 3 columns]

In [467]:
#for calculating the final price after discount and total amount after discount
df['discount'] = pd.to_numeric(df['discount'], errors='coerce').fillna(0)
df['final_price'] = (df['initial_price'] * (1 - (df['discount'] / 100))).round(2)
#using the rating column to determine the quantity of each product, assuming higher ratings indicate more purchases
df['rating'] = pd.to_numeric(df['rating'], errors='coerce').fillna(0)
df['quantity'] = df['rating'].round().astype(int).apply(lambda x: 1 if x == 0 else x)

df['total_amount'] = (df['final_price'] * df['quantity']).round(2)

df[['initial_price', 'discount', 'final_price', 'quantity', 'total_amount']].head()

   initial_price  discount  final_price  quantity  total_amount
0           3995      58.0      1677.90         4       6711.60
1           2899      35.0      1884.35         4       7537.40
2           2999      65.0      1049.65         4       4198.60
3           1675      52.0       804.00         4       3216.00
4           2899      17.0      2406.17         5      12030.85

In [468]:
category_summary = df.groupby('category')['total_amount'].sum()
category_summary

category
backpacks                21663.60
bath-robe                12030.85
bath-towels               1958.60
bathroom-accessories      5596.00
bedsheets                43730.13
                          ...
tunics                   10975.20
wall-art                  2240.00
wallets                  36542.60
watches                 203969.90
yoga-mats                 1929.24
Name: total_amount, Length: 97, dtype: float64

In [469]:
# To Remove Corrupted Blocks from Seller Information Columns
import re

def clear_corrupted_blocks(text):
    if isinstance(text, str):
        cleaned = re.sub(r'[^\x00-\x7F]+', '', text)
        cleaned = re.sub(r'[\x00-\x1F\x7F]', '', cleaned)
        return cleaned.strip()
    return text

columns_to_clean = ['seller_name', 'seller_info', 'seller_information']

for col in columns_to_clean:
    if col in df.columns:
        df[col] = df[col].apply(clear_corrupted_blocks)

df.to_csv('cleaned_dataset.csv', index=False, encoding='utf-8-sig')